# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97d8a69b7ecad9d8b9f2a7d10b5190431579103446b01f016f3a3707692e73821521eacab2e0e69d425ffb450430812916607ff56f816060faea6fc109f5c9d4

test:
  secret_key_base: 7e7c03b1c5c1a0057a71b2e7b9c5f720dfb7fef800431cd46e86b0aa7c6d1ab224a0ff4fc7a3ac88b4e6c02eadd6108d6a388c9925f4ceec98c21abdcb0f9eff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
